### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by mul0** [securestate/king-phisher#68] opened 2016-02-09 21:16 UTC
When selecting the View Campaign tab on the client a TypeError occurs. Any help appreciated.

Error Type: exceptions.TypeError
Error Details: TypeError("Couldn't find foreign struct converter for 'cairo.Context'",)
Error UID: 56435b34-1fe9-46e1-988e-3b135aaec401
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.1.0
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 2.7.11
Gtk Version: 3.18.7
Timezone: America/New_York

Thread Information:
 => MainThread (alive=True daemon=False)

Stack Trace:
Traceback (most recent call last):
  File "/usr/share/king-phisher/king_phisher/client/windows/main.py", line 255, in signal_notebook_switch_page
    notebook.emit('switch-page', notebook.get_nth_page(index), index)
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

**Comment by zeroSteiner** [comment] 2016-02-09 21:50
Thank you for reporting this, I was able to reproduce it and find a solution. Please `apt-get install python-gi-cairo` and then restart the client. It would appear as though the Kali package maintainers forgot to include that as a dependency. I'll open an issue with them to have it addressed.

**Comment by zeroSteiner** [comment] 2016-02-09 21:59
Just reported this issue on the [Kali Bug Tracker](https://bugs.kali.org/view.php?id=3054) please pardon the arbitrary username.

**Comment by mul0** [comment] 2016-02-09 22:15
Perfect, this has resolve the issue.

**Comment by zeroSteiner** [comment] 2016-02-09 22:27
Thanks I'm going to close this out then because the issue is has been reported to the Kali maintainers.

**Closed by zeroSteiner** 2016-02-09 22:27 UTC
Labels: bug
