### ISSUE TITLE
Headers in Message

### ISSUE THREAD

**Issue by secureality** [securestate/king-phisher#294] opened 2018-05-01 21:56 UTC
I do not believe this is a bug, but perhaps some insight into how King Phisher handles the MIME headers might be helpful, or another idea on how to handle this issue.

I have enabled the "Custom Message MIME Headers" plugin, and configured a header for:
Disposition-Notification-To: testing@infnx.net
This has worked for years in my prior mail routine.

When I receive the e-mail, my client does not trigger the normal "Return Receipt Requested" notification message.  If I enclose the email address in quotes (Disposition-Notification-To: "testing@infnx.net"), then the return receipt message is triggered, but I get a message that "there are non-ASCII characters in the local part of the recipient address" error.  When comparing the headers from an old message (non-KP) to a new KP generated message, the difference appears to be related to encoding.

Here is a snippet of the headers from an 'old' message:

```
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_1513266095272520"
MIME-Version: 1.0
Date: Thu, 14 Dec 2017 10:41:35 -0500
From: Infinix <testing@infnx.net>
To: testing@infnx.net
Subject: <redacted>
Disposition-Notification-To: testing@infnx.net
<other extra message details deleted>
--_----------=_1513266095272520`
```
Snippet from a 'new' message:
```
Content-Type: multipart/related; charset="utf-8"; boundary="===============0747124701=="
MIME-Version: 1.0
Subject: <redacted>
reply-to: testing@infnx.net
From: "Infinix" <testing@infnx.net>
Date: Tue, 01 May 2018 17:08:44 -0400
To: <testing@infnx.net>
Disposition-Notification-To: "testing@infnx.net"
<other extra message details deleted>
--===============0747124701==
```

The differences that I notice are:
1) the 'old' message uses Content-Transfer-Encoding: binary, the 'new' message doesn't appear to use this;
2) The content-type uses a charset of UTF-8 in the 'new', and was not specified in the 'old'.

So it appears that either the UTF-8 encoding or transfer encoding doesn't get interpreted by the client unless quoted, but then can't parse the return e-mail address, or the Content-Transfer-Encoding is impacting the interpretation of the headers.

Any thoughts or suggestions on how to get around this issue?  I just want to get a return receipt as it is something I report back on spear phishing exercises.

Any suggestions are appreciated, and thanks for your time!

-John

**Comment by zeroSteiner** [comment] 2018-05-01 22:40
Where exactly are you seeing the "there are non-ASCII characters in the local part of the recipient address" error? In King Phisher or somewhere else?

**Comment by secureality** [comment] 2018-05-01 22:55
I am seeing that in the e-mail client (actually, in several different e-mail clients), although you can see in the headers there aren't any.

**Comment by zeroSteiner** [comment] 2018-05-02 00:30
Ok can you be even more specific? Which email client and where is this error located? What would be even better is if you could provide a screenshot of where you're seeing this error in say Outlook, GMail, Thunderbird etc.

Also are you seeing this error only when you're specifying the `Disposition-Notification-To` header? The reason I ask is, I find it odd that you'd see an error regarding the recipient address only when specifying this header. It could be unrelated but I don't know, I'd need to see if I could reproduce it hence all the details I'm requesting to guide me in finding the error message.

**Comment by secureality** [comment] 2018-05-02 02:29
No problem, I appreciate your assistance.  My default client is Thunderbird, but seeing similar characteristics in GMail. Here are screen shots:

Plugin config (plain Disposition-Notification-To: header):
![image](https://user-images.githubusercontent.com/28160854/39502104-72acd042-4d8c-11e8-8078-1ed17d3e7409.png)
Here is the result - notice that there is no Return Receipt notification
![image](https://user-images.githubusercontent.com/28160854/39502167-cc316b28-4d8c-11e8-87f9-7bec1bc99b7e.png)

Change the header to enclose return address in quotes:
![image](https://user-images.githubusercontent.com/28160854/39502259-3abeb71c-4d8d-11e8-8694-bbdfe92bb131.png)

Here is the result - I get the "Send Receipt" notification.
![image](https://user-images.githubusercontent.com/28160854/39502245-25dd3daa-4d8d-11e8-960a-77179aa2e2db.png)

but, if I try to "Send Receipt", I get:
![image](https://user-images.githubusercontent.com/28160854/39502296-66bb65ea-4d8d-11e8-89bb-d77ffa9536e7.png)

The plain Dispo-Not-To header (with no quotes, brackets, or anything else) has always worked in the past for me, that why I am assuming it has something to do with the encoding.  In the mean time, I have tried single quotes, the more complete "Name <email@someplace.com>" syntax, and variations of quoting the brackets, quoting just the "@" and other combinations.

BTW, running KP 1.11.0 client on Windows, KingPhisherServer Version: 1.11.1 (rev: 0d6c0c19f0c2) on Ubuntu 16.04.

**Comment by zeroSteiner** [comment] 2018-05-02 02:32
Thanks, with that information I should have enough to start really looking into this. I'll let you know if I have more questions.

**Comment by zeroSteiner** [comment] 2018-05-03 02:36
Cool, thanks for the additional information!

**Comment by zeroSteiner** [comment] 2018-05-08 15:29
Well I'm having a hard time reproducing this. I'm pretty sure that the proper header syntax should be: `Disposition-Notification-To: <target@domain.com>` though. I'm getting a proper request for a receipt in Outlook and no character complaints. I have noticed that the SMTP server I'm using will append the domain afterwards if I use double quotes, making the string invalid but that seems like a configuration issue with my server.

**Comment by zeroSteiner** [comment] 2018-05-30 12:39
Alright I'm going to close this out since I can't reproduce it. If you're still experiencing the issue, just comment here and I'll reopen it.

**Closed by zeroSteiner** 2018-05-30 12:39 UTC

**Comment by secureality** [comment] 2018-06-01 02:21
Sorry for my lack of response, Z, I've been on the road myself.  I have no additional info to help you reproduce, closing it is appropriate.  If I find any more info, I will update.  Thanks for your assistance, it is appreciated.

Been keeping an eye out on some of your work in Metasploit -- nice work!  One day I'll have the skills to contribute more, I am always looking for opportunities to help.
