### ISSUE TITLE
SSL cert error

### ISSUE THREAD

**Issue by kureeoffsec** [securestate/king-phisher#147] opened 2016-08-24 13:42 UTC
When connecting to a mail server with a self signed SSL cert, king-phisher fails to send emails with the error:

WARNING  received a socket.error while connecting to the SMTP server

Would it be possible to add an option to either disable the ssl cert checks, or accept the self signed cert?

**Comment by zeroSteiner** [comment] 2016-08-31 15:24
I looked into this a bit and it doesn't seem feasible to prompt the user to select a certificate for two reasons.
1) The certificate can be invalid for a number of reasons (hostname mismatch, expired etc.)
2) Creating a GUI widget to accurately display the information for the certificate is a bit out of the scope of the project as it would not be a trivial endeavor.

It looks like this would have to be implemented as an all or nothing option. Either the certificate will be validated entirely by the system, or the check would be disabled by the user via some configuration option.

**Comment by zeroSteiner** [comment] 2016-09-20 19:49
@kureeoffsec I'm having trouble reproducing this error can you provide some more details? Specifically I'd like to know exactly what version of Python you're using (major, minor and patch please) as well as if your connecting to your SMTP server with TLS natively or using STARTTLS. Also providing the log messages before and after the message may be helpful.

**Comment by kureeoffsec** [comment] 2016-09-27 19:53
Hey man, I have been out of the country for awhile, and will get back to
you asap.

**Comment by zeroSteiner** [comment] 2016-10-29 20:40
This has been open for over a month so I'm going to close it out now. If you get a chance and want to discuss it further just comment on this thread and I'd be happy to reopen it.

**Closed by zeroSteiner** 2016-10-29 20:40 UTC
Labels: can't reproduce, feature request
