### ISSUE TITLE
installation issues on ubuntu

### ISSUE THREAD

**Issue by seanjackson** [securestate/king-phisher#20] opened 2015-04-09 21:02 UTC

**Comment by seanjackson** [comment] 2015-04-09 21:03
edmond@Edmond:~/Desktop/king-phisher-master$ sudo apt-get install python-pip
Reading package lists... Done
Building dependency tree      
Reading state information... Done
python-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 344 not upgraded.
edmond@Edmond:~/Desktop/king-phisher-master$ wget -q https://github.com/securestate/king-phisher/raw/master/tools/install.sh && sudo bash ./install.sh
Linux version detected as Ubuntu
Downloading and installing the King Phisher server to /opt/king-phisher
The directory '/home/edmond/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/edmond/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/edmond/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): six>=1.7.0 in /usr/local/lib/python3.4/dist-packages
The directory '/home/edmond/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/edmond/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/edmond/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting alembic>=0.6.7 (from -r requirements.txt (line 3))
  Downloading alembic-0.7.5.post2.tar.gz (616kB)
    100% |████████████████████████████████| 618kB 195kB/s
  Exception:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.4/dist-packages/pip/basecommand.py", line 246, in main
      status = self.run(options, args)
    File "/usr/local/lib/python3.4/dist-packages/pip/commands/install.py", line 342, in run
      requirement_set.prepare_files(finder)
    File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 345, in prepare_files
      functools.partial(self._prepare_file, finder))
    File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 290, in _walk_req_to_install
      more_reqs = handler(req_to_install)
    File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 502, in _prepare_file
      abstract_dist.prep_for_dist()
    File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 123, in prep_for_dist
      self.req_to_install.run_egg_info()
    File "/usr/local/lib/python3.4/dist-packages/pip/req/req_install.py", line 363, in run_egg_info
      self.setup_py, self.name,
    File "/usr/local/lib/python3.4/dist-packages/pip/req/req_install.py", line 334, in setup_py
      import setuptools  # noqa
    File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 11, in <module>
      from setuptools.extension import Extension
    File "/usr/local/lib/python3.4/dist-packages/setuptools/extension.py", line 8, in <module>
      from .dist import _get_unpatched
    File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 21, in <module>
      packaging = pkg_resources.packaging
  AttributeError: 'module' object has no attribute 'packaging'

Installing the client desktop application file
Updating the GTK icon cache
gtk-update-icon-cache: Cache file created successfully.
Installing the King Phisher upstart service file in /etc/init/
Starting the King Phisher service
king-phisher start/running, process 3298
edmond@Edmond:~/Desktop/king-phisher-master

**Comment by seanjackson** [comment] 2015-04-09 21:04
review for me cannot figure out the problem

**Comment by zeroSteiner** [comment] 2015-04-10 12:25
It still looks like you're experiencing issues with pip, after a quick google search it looks like the problem is similar to [this](https://github.com/nltk/nltk/issues/824#issuecomment-68488853) and that ```sudo pip install setuptools==9.1``` might fix the issue but I can not confirm that.

It also looks like you're using Python 3.4 which is odd because last I checked the default python version on Ubuntu is 2.7. King Phisher is a little bit away from support 3.x and requires an alternative requirements.txt file. In short, trying to use the automated install script with Python 3.x set as the default Python version won't work.

**Comment by seanjackson** [comment] 2015-04-10 16:48
wget -q https://github.com/securestate/king-phisher/raw/master/tools/install.sh && sudo bash ./install.sh 
Linux version detected as Ubuntu
Downloading and installing the King Phisher server to /opt/king-phisher
Installing Ubuntu dependencies
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
Installing Python package dependencies from pypi
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
ImportError: No module named 'pip'
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
ImportError: No module named 'pip'
Installing the client desktop application file
Updating the GTK icon cache
gtk-update-icon-cache: Cache file created successfully.
Installing the King Phisher upstart service file in /etc/init/
Starting the King Phisher service
king-phisher start/running, process 5398
edmond@Edmond:~$

**Comment by seanjackson** [comment] 2015-04-10 16:49
am really sorry for disturbing you over this pip issue,just that i have a presentation to make on monday with the kingPhisher

**Comment by zeroSteiner** [comment] 2015-04-12 17:15
The error messages seem to be implying that apt-get cant not run because another process is already installing packages. Make sure apt-get is not already running before you the install script. Also ensure that your system is fully up to date by running ```sudo apt-get update; sudo apt-get upgrade```.

Are you running Ubuntu 14.04 workstation and if so is it the standard Ubuntu 14.04 image (with the GNOME desktop environment) or something different?

You also did not respond about why it appears that you are using Python 3.4 and not Python 2.7. The error messages saying that Python 2.7 is being used implies that something is not configured in the way that I would expect it to be. At a bare minimum please check the default python version by running ```python -V``` and pasting the output into this thread.

**Comment by seanjackson** [comment] 2015-04-14 16:38
edmond@Edmond:~/Desktop$ python -v
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/lib/python2.7/site.pyc matches /usr/lib/python2.7/site.py
import site # precompiled from /usr/lib/python2.7/site.pyc
# /usr/lib/python2.7/os.pyc matches /usr/lib/python2.7/os.py
import os # precompiled from /usr/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /usr/lib/python2.7/posixpath.pyc matches /usr/lib/python2.7/posixpath.py
import posixpath # precompiled from /usr/lib/python2.7/posixpath.pyc
# /usr/lib/python2.7/stat.pyc matches /usr/lib/python2.7/stat.py
import stat # precompiled from /usr/lib/python2.7/stat.pyc
# /usr/lib/python2.7/genericpath.pyc matches /usr/lib/python2.7/genericpath.py
import genericpath # precompiled from /usr/lib/python2.7/genericpath.pyc
# /usr/lib/python2.7/warnings.pyc matches /usr/lib/python2.7/warnings.py
import warnings # precompiled from /usr/lib/python2.7/warnings.pyc
# /usr/lib/python2.7/linecache.pyc matches /usr/lib/python2.7/linecache.py
import linecache # precompiled from /usr/lib/python2.7/linecache.pyc
# /usr/lib/python2.7/types.pyc matches /usr/lib/python2.7/types.py
import types # precompiled from /usr/lib/python2.7/types.pyc
# /usr/lib/python2.7/UserDict.pyc matches /usr/lib/python2.7/UserDict.py
import UserDict # precompiled from /usr/lib/python2.7/UserDict.pyc
# /usr/lib/python2.7/_abcoll.pyc matches /usr/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /usr/lib/python2.7/_abcoll.pyc
# /usr/lib/python2.7/abc.pyc matches /usr/lib/python2.7/abc.py
import abc # precompiled from /usr/lib/python2.7/abc.pyc
# /usr/lib/python2.7/_weakrefset.pyc matches /usr/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /usr/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /usr/lib/python2.7/copy_reg.pyc matches /usr/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /usr/lib/python2.7/copy_reg.pyc
# /usr/lib/python2.7/traceback.pyc matches /usr/lib/python2.7/traceback.py
import traceback # precompiled from /usr/lib/python2.7/traceback.pyc
# /usr/lib/python2.7/sysconfig.pyc matches /usr/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /usr/lib/python2.7/sysconfig.pyc
# /usr/lib/python2.7/re.pyc matches /usr/lib/python2.7/re.py
import re # precompiled from /usr/lib/python2.7/re.pyc
# /usr/lib/python2.7/sre_compile.pyc matches /usr/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /usr/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /usr/lib/python2.7/sre_parse.pyc matches /usr/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /usr/lib/python2.7/sre_parse.pyc
# /usr/lib/python2.7/sre_constants.pyc matches /usr/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /usr/lib/python2.7/sre_constants.pyc
# /usr/lib/python2.7/_sysconfigdata.pyc matches /usr/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /usr/lib/python2.7/_sysconfigdata.pyc
# /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc matches /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py
import _sysconfigdata_nd # precompiled from /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc
# /usr/lib/python2.7/sitecustomize.pyc matches /usr/lib/python2.7/sitecustomize.py
import sitecustomize # precompiled from /usr/lib/python2.7/sitecustomize.pyc
import encodings # directory /usr/lib/python2.7/encodings
# /usr/lib/python2.7/encodings/__init__.pyc matches /usr/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /usr/lib/python2.7/encodings/__init__.pyc
# /usr/lib/python2.7/codecs.pyc matches /usr/lib/python2.7/codecs.py
import codecs # precompiled from /usr/lib/python2.7/codecs.pyc
import _codecs # builtin
# /usr/lib/python2.7/encodings/aliases.pyc matches /usr/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /usr/lib/python2.7/encodings/aliases.pyc
# /usr/lib/python2.7/encodings/utf_8.pyc matches /usr/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /usr/lib/python2.7/encodings/utf_8.pyc
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
dlopen("/usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so", 2);
import readline # dynamically loaded from /usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so
>>>

**Comment by seanjackson** [comment] 2015-04-14 16:38
edmond@Edmond:~/Desktop$ python -v
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/lib/python2.7/site.pyc matches /usr/lib/python2.7/site.py
import site # precompiled from /usr/lib/python2.7/site.pyc
# /usr/lib/python2.7/os.pyc matches /usr/lib/python2.7/os.py
import os # precompiled from /usr/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /usr/lib/python2.7/posixpath.pyc matches /usr/lib/python2.7/posixpath.py
import posixpath # precompiled from /usr/lib/python2.7/posixpath.pyc
# /usr/lib/python2.7/stat.pyc matches /usr/lib/python2.7/stat.py
import stat # precompiled from /usr/lib/python2.7/stat.pyc
# /usr/lib/python2.7/genericpath.pyc matches /usr/lib/python2.7/genericpath.py
import genericpath # precompiled from /usr/lib/python2.7/genericpath.pyc
# /usr/lib/python2.7/warnings.pyc matches /usr/lib/python2.7/warnings.py
import warnings # precompiled from /usr/lib/python2.7/warnings.pyc
# /usr/lib/python2.7/linecache.pyc matches /usr/lib/python2.7/linecache.py
import linecache # precompiled from /usr/lib/python2.7/linecache.pyc
# /usr/lib/python2.7/types.pyc matches /usr/lib/python2.7/types.py
import types # precompiled from /usr/lib/python2.7/types.pyc
# /usr/lib/python2.7/UserDict.pyc matches /usr/lib/python2.7/UserDict.py
import UserDict # precompiled from /usr/lib/python2.7/UserDict.pyc
# /usr/lib/python2.7/_abcoll.pyc matches /usr/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /usr/lib/python2.7/_abcoll.pyc
# /usr/lib/python2.7/abc.pyc matches /usr/lib/python2.7/abc.py
import abc # precompiled from /usr/lib/python2.7/abc.pyc
# /usr/lib/python2.7/_weakrefset.pyc matches /usr/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /usr/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /usr/lib/python2.7/copy_reg.pyc matches /usr/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /usr/lib/python2.7/copy_reg.pyc
# /usr/lib/python2.7/traceback.pyc matches /usr/lib/python2.7/traceback.py
import traceback # precompiled from /usr/lib/python2.7/traceback.pyc
# /usr/lib/python2.7/sysconfig.pyc matches /usr/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /usr/lib/python2.7/sysconfig.pyc
# /usr/lib/python2.7/re.pyc matches /usr/lib/python2.7/re.py
import re # precompiled from /usr/lib/python2.7/re.pyc
# /usr/lib/python2.7/sre_compile.pyc matches /usr/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /usr/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /usr/lib/python2.7/sre_parse.pyc matches /usr/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /usr/lib/python2.7/sre_parse.pyc
# /usr/lib/python2.7/sre_constants.pyc matches /usr/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /usr/lib/python2.7/sre_constants.pyc
# /usr/lib/python2.7/_sysconfigdata.pyc matches /usr/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /usr/lib/python2.7/_sysconfigdata.pyc
# /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc matches /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py
import _sysconfigdata_nd # precompiled from /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc
# /usr/lib/python2.7/sitecustomize.pyc matches /usr/lib/python2.7/sitecustomize.py
import sitecustomize # precompiled from /usr/lib/python2.7/sitecustomize.pyc
import encodings # directory /usr/lib/python2.7/encodings
# /usr/lib/python2.7/encodings/__init__.pyc matches /usr/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /usr/lib/python2.7/encodings/__init__.pyc
# /usr/lib/python2.7/codecs.pyc matches /usr/lib/python2.7/codecs.py
import codecs # precompiled from /usr/lib/python2.7/codecs.pyc
import _codecs # builtin
# /usr/lib/python2.7/encodings/aliases.pyc matches /usr/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /usr/lib/python2.7/encodings/aliases.pyc
# /usr/lib/python2.7/encodings/utf_8.pyc matches /usr/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /usr/lib/python2.7/encodings/utf_8.pyc
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
dlopen("/usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so", 2);
import readline # dynamically loaded from /usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so
>>>

**Comment by seanjackson** [comment] 2015-04-14 16:39
when i ran the python -v command it seems like am running python 2.7
i think i will have to update my system

**Comment by zeroSteiner** [comment] 2015-04-14 16:42
That was supposed to be ```python -V``` (note the capital V), to just print the version. 2.7 is the correct version however it looked like pip was using Python 3.4. You're installation issues are stemming from your non-functioning pip.

**Comment by seanjackson** [comment] 2015-04-14 17:04
I ran the python -V i am using python 2.7.6

**Comment by seanjackson** [comment] 2015-04-14 17:10
i can't seem to figure the problem,i will ensure try to make sure my system is up to date

**Comment by zeroSteiner** [comment] 2015-04-14 17:11
Yes so you need to address the issue of why pip is using Python 3. If you run the command ```pip -V``` (not the capital V again) my guess is that it's going to say Python 3.4 at the end which is a problem because it's installing the packages for Python 3.4. If you symlinked pip to pip3 using ```ln -s``` that could be contributing to the issue.

**Comment by seanjackson** [comment] 2015-04-14 17:14
i have uninstalled the python 3.4 package i want to update the sytem

**Comment by seanjackson** [comment] 2015-04-14 17:20
edmond@Edmond:~/Desktop$ pip -v
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
ImportError: No module named 'pip'

**Comment by seanjackson** [comment] 2015-04-14 17:21
i need to update my system to see wheather i can fix the pip issue

**Comment by zeroSteiner** [comment] 2015-04-14 18:11
If it is a practical option, starting with a fresh Ubuntu 14.04 installation might be your best option. Just do a fresh install and then an apt-get update and an apt-get upgrade.

**Comment by zeroSteiner** [comment] 2015-04-21 15:01
This issue has been open for a week without comment, so I'm going to go ahead and close it. If you make progress on fixing your issues with PIP and continue to run into additional issues you can either re-comment on this one or open a new issue if the problem is different.

**Closed by zeroSteiner** 2015-04-21 15:01 UTC
Labels: install
