### ISSUE TITLE
Generating user ids

### ISSUE THREAD

**Issue by mozg31337** [securestate/king-phisher#257] opened 2018-01-22 13:32 UTC
Hello,

sorry if this is the wrong way of asking about a function of the project. I have two requirements that I was hoping to make them work with king-phisher. High level overview - I need to automatically generate a word/excel attachment that includes the unique user id. I need to send the generated attachments to each of the users. The idea is to be able to track users that open the attachments.

1. Is it possible to pre-generate a list of user's unique ids that will be used for sending emails?
2. Is it possible to attach files for each individual user? The file names could actually contain the unique user ids in their names, like document-{{uid}}.docx or something like that.
3. Basic reporting on who opened the attachment.

Can any of these features be implemented in the project or already exist? I would be happy to commission this work at reasonable cost.

Many thanks

Andrei

**Comment by zeroSteiner** [comment] 2018-01-22 13:36
We've looked into this in the past (see #135). The issue is finding the technical resources to generate a word document from what would have to be a sort of template file.

We can look into the other requests though.

**Comment by mozg31337** [comment] 2018-01-22 13:57
Thanks for getting back so quickly. 

The macro word documents are not really reliable nowadays as a lot of anti malware block/flag documents that have macro in them. 

There is another route that could work. 

1. There are python apps that work with ms office docs and modify its footer to include an image file. This is loaded automatically when the document is opened. Somewhat similar to what you use to track email opening with the tracker image. This could be used to automatically generate the ms office docs. Something similar to what http://canarytokens.org/generate use. They generate a few types of attachment, including PDF and ms office documents. 

2. Another route is to use something that is described here: https://rhinosecuritylabs.com/research/abusing-microsoft-word-features-phishing-subdoc/. The method uses the subDoc function in the word document. They have a python app that automatically generates the document, which could be used in the king-phisher perhaps? However, the exact method described in the link is not really going to work well at mass as most companies are blocking egress smb traffic. But at least there are python tools that could be used to automatically generate ms documents. 

In any case, the automatically pre-generated uids and attachments per uid functionalities are a long way toward achieving an automated attachment tracking that could be used by kingphisher. 

Cheers 

Andrei

**Comment by zeroSteiner** [comment] 2018-01-25 13:57
We have a plugins that have functionality similar to both of these.

For the first one, I'd recommend looking at the [pdf_generator](https://github.com/securestate/king-phisher-plugins/blob/master/client/pdf_generator.py) plugin. As the name implies, it'll generate a PDF document, but it is rendered as a template and can thus use UID variables etc.

For the second one, we actually already have a plugin which does that called [phishery_docx](https://github.com/securestate/king-phisher-plugins/blob/master/client/phishery_docx.py). It's based off of the Phishery tool.

**Comment by zeroSteiner** [comment] 2018-02-02 15:22
I'm going to close this issue out. If you want to discuss things further, our [slack](https://king-phisher-slackin.herokuapp.com/) might be a better place to do it.

**Closed by zeroSteiner** 2018-02-02 15:22 UTC
Labels: duplicate
