### ISSUE TITLE
Problem Sending Emails with Versions 0.1.6 & 0.1.7

### ISSUE THREAD

**Issue by snider14** [securestate/king-phisher#38] opened 2015-09-15 14:36 UTC
We have been using King Phisher for most of the year, but today can no longer send emails using the tool. Just yesterday the tool was working flawlessly, but today it does nothing when I press "start" to send email. I am wondering if you have any suggestions to what needs to be done or what could cause a chance all of the sudden. Thanks!

**Comment by zeroSteiner** [comment] 2015-09-15 15:01
It sounds like it it's having trouble connecting to the SMTP server. You should see messages appearing in the output box. Furthermore, both 0.1.6 and 0.1.7 are very old (3 versions behind) and you should update to 0.3 when you get a chance.

**Comment by snider14** [comment] 2015-09-15 15:05
When I press start on the send tab it does nothing, does not even appear to be attempting to send. The start button is always "clickable" and the stop and pause are not. This worked perfectly fine yesterday, so I am not sure what has changed. If there was an issue with the server then I should get an error.

**Comment by zeroSteiner** [comment] 2015-09-15 15:16
If you're not running it on Windows, you can run the client from the command line and pass the `-L DEBUG` option to get the log output. Putting that into the issue might help me determine what is happening.

**Comment by snider14** [comment] 2015-09-15 17:15
The reason we have not upgraded is because we would be using redhat 7, which is not supported by king phisher. Do you know when KP will support redhat 7? Also KP is on a linux server, from which -L DEBUG does not seem to be a valid command. Does this need to be done differently for Linux? Thanks for the help.

**Comment by zeroSteiner** [comment] 2015-09-15 17:55
We don't currently have plans to support Red Hat due to me being unable to get a copy for testing. The current server that is running King Phisher should at least be upgradable from it's current version to 0.3 without changing the host OS.

Also the -L DEBUG is the option to pass to the client, like `./KingPhisher -L DEBUG`. It's important to get the logs from the client because that is the component that is responsible for sending the phishing emails.

**Comment by snider14** [comment] 2015-09-15 18:16
Sorry, but from a command line I can not run -L DEBUG. I attempt to and it is not recognized. I am running it from a command line on my PC for where the KP client is stored.

**Comment by zeroSteiner** [comment] 2015-09-15 18:21
So to confirm, you have the Linux client installed correct? Also thats not a command, it's the arguments to the King Phisher client. You need to run the client from the command line. First change directory to where King Phisher is installed using `cd`. Then run the full command `./KingPhisher -L DEBUG` and it should produce a large amount of text output as the client starts. From there you can reproduce the issue and copy the logs from the terminal.

**Comment by snider14** [comment] 2015-09-15 18:45
sorry, we have the client loaded on our windows and the application server is linux. we are currently trying to upgrade and see if that resolves the issue.

**Comment by snider14** [comment] 2015-09-15 18:54
This is a screenshot of the error we keep getting after upgrading application server.

![image](https://cloud.githubusercontent.com/assets/14295632/9886727/baf875ee-5bb9-11e5-8767-44bef80ac368.png)

**Comment by zeroSteiner** [comment] 2015-09-15 19:01
It's complaining that the server does not have the required `geoip.database` setting. That was added in one of the later version (0.2 I believe). You can find the template configuration [here](https://github.com/securestate/king-phisher/blob/master/data/server/king_phisher/server_config.yml) which has the default options for new installations. Specifically [lines 42-44](https://github.com/securestate/king-phisher/blob/8145708af2d7e222c8ffb7a78c37330f95b7a1f7/data/server/king_phisher/server_config.yml#L42-L44) have the geoip configuration.

Also prior to starting the server you can verify the King Phisher server configuration using the command: `sudo ./KingPhisherServer --verify-config server_config.yml` and it should say configuration verification passed if there are no other missing options.

**Comment by snider14** [comment] 2015-09-15 19:32
How do you apply the configurations from .2 that are missing? When updating it does not give you the syntax for this. Below are the commands to run when upgrading as well as the link to the page we used for updating server. Thanks

![image](https://cloud.githubusercontent.com/assets/14295632/9887702/fda175b2-5bbe-11e5-9877-119871586ba8.png)

https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher

**Comment by zeroSteiner** [comment] 2015-09-15 19:36
You need to edit the server's configuration file. Use a text editor like nano if you're in the command line or an application like gedit if you're in a graphical environment. The missing settings need to be added to the existing configuration file.

**Comment by snider14** [comment] 2015-09-15 19:43
We will work on this. Thanks for all the help thus far!

**Comment by zeroSteiner** [comment] 2015-09-15 19:57
Ok thanks, I'm going to go ahead and close the issue out then. If you are still having trouble after updating just go ahead and open a new one.

**Closed by zeroSteiner** 2015-09-15 19:57 UTC
