### ISSUE TITLE
simplejson

### ISSUE THREAD

**Issue by TheUnable** [securestate/king-phisher#331] opened 2018-10-25 01:37 UTC
having issues with king-phisher...upgraded kali got this issue...

Traceback (most recent call last):
  File "./KingPhisher", line 49, in <module>
    from king_phisher.client import application
  File "/usr/share/king-phisher/king_phisher/client/application.py", line 61, in <module>
    from king_phisher.client.windows import main
  File "/usr/lib/python3/dist-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
  File "/usr/share/king-phisher/king_phisher/client/windows/__init__.py", line 33, in <module>
    from .main import *
  File "/usr/lib/python3/dist-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
  File "/usr/share/king-phisher/king_phisher/client/windows/main.py", line 40, in <module>
    from king_phisher.client import export
  File "/usr/lib/python3/dist-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
  File "/usr/share/king-phisher/king_phisher/client/export.py", line 54, in <module>
    import geojson
  File "/usr/lib/python3/dist-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
  File "/usr/lib/python3/dist-packages/geojson/__init__.py", line 1, in <module>
    from geojson.codec import dump, dumps, load, loads, GeoJSONEncoder
  File "/usr/lib/python3/dist-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
  File "/usr/lib/python3/dist-packages/geojson/codec.py", line 11, in <module>
    class GeoJSONEncoder(json.JSONEncoder):
AttributeError: module 'simplejson' has no attribute 'JSONEncoder'

**Comment by zeroSteiner** [comment] 2018-10-25 01:52
What version of simplejson are you using? Check with `python3 -m pip freeze | grep -i simplejson`. Looks like another upstream compatibility error.

**Comment by zeroSteiner** [comment] 2018-10-25 01:56
Can you please check geojson too?

**Comment by TheUnable** [comment] 2018-10-25 13:21
simplejson==3.15.0
geojson==2.4.1

those are the versions and thank you for helping

**Comment by zeroSteiner** [comment] 2018-10-25 13:51
Well I'm confused because I installed both of those versions and can not reproduce this. The error seems to be complaining that `simplejson` does not have `simplejson.JSONEncoder` which from what I can tell it does:
```
Python 3.6.6 (default, Jul 19 2018, 14:25:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import simplejson

In [2]: simplejson.__version__
Out[2]: '3.15.0'

In [3]: simplejson.JSONEncoder
Out[3]: simplejson.encoder.JSONEncoder
```

From what I can tell from glancing through `geojson` the `simplejson` module isn't necessary. We don't even require it in King Phisher. I'd propose you take one of two solutions to fix this:
1. You could just uninstall it with `python3 -m pip uninstall simplejson` and that should fix your King Phisher issue, but that package won't be available for whatever else you might need.
1. We've actually taken steps to address these kinds of dependency problems and they're live in the `dev` branch. We're a couple of weeks from merging them into master, but if you don't want to uninstall `simplejson` system-wide, you could opt into [Beta Testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).

**Comment by TheUnable** [comment] 2018-10-25 14:19
is it possible to send to me to direct download of the beta since git fetch is being a pain to me

**Comment by wolfthefallen** [comment] 2018-10-25 14:22
@TheUnable  How is it being a pain? Can you provide an output of you trying to switch to the dev branch?

**Comment by TheUnable** [comment] 2018-10-25 14:23
here you go my friend
fatal: not a git repository (or any of the parent directories): .git

**Comment by wolfthefallen** [comment] 2018-10-25 14:31
ok that means either you installed via `apt` on `kali` or you download a compressed release.

I would recommend backing up your server configuration file ( `server_config.yml` ) to another location.
Then clone down the King Phisher project then switch over to dev.

```Shell
cd #to directory of choice normally /opt/
git clone https://github.com/securestate/king-phisher.git
```
follow the wiki to changing to the dev branch
Copy your `server_config.yml` backup into the king-phisher directory.
run the `tools\install.sh`

**Comment by zeroSteiner** [comment] 2018-10-25 14:48
@wolfthefallen is right. Once you're done though you should be able to verify you're on the right version by running `./KingPhisher --version` and you should see `... Version: 1.12.0-beta2...` in the output.

**Comment by zeroSteiner** [comment] 2018-10-25 15:30
So that should be fixed when your run `sudo tools/install.sh --update` from the beta-testing branch (version "1.12.0-beta2"). Is there a chance you forgot that step? That should have installed that missing package. I don't think Parrot OS was one we tested (@wolfthefallen can you chime in here) but it should be fine since it uses the same packages as Ubuntu or Kali or whatever which we do test.

**Comment by wolfthefallen** [comment] 2018-10-25 15:34
We do not support Parrort OS..
please provide the output of 
`apt search gir1.2-webkit`

**Comment by TheUnable** [comment] 2018-10-25 15:36
serious thank you guys for your time and help..
here is the output

gir1.2-webkit2-4.0/kali-rolling,stable,now 2.22.2-1 amd64 [installed,automatic]
  Web content engine library for GTK+ - GObject introspection data

**Comment by wolfthefallen** [comment] 2018-10-25 15:37
thank you, give me a few minutes and i'll update the dev branch with a fix

**Comment by wolfthefallen** [comment] 2018-10-25 15:53
ok the fix has been added in commit f486c26352b06648cbee6e2c20c1f191397b1245 into the dev branch.

Do a `git fetch` and `git pull` to update your King Phisher, then do a `git log` and the top entry should be
```
commit f486c26352b06648cbee6e2c20c1f191397b1245 (HEAD -> dev, upstream/dev, origin/dev)
Author: Erik Daguerre <etphonehm2003@gmail.com>
Date:   Thu Oct 25 11:50:05 2018 -0400

    Added gir1.2-webkit-4.0 to install.sh
```

Once you have that confirmed, run `tools/install.sh` and you should be good to go.

**Comment by TheUnable** [comment] 2018-10-25 16:21
says no module named gi but i have pygobject installed

**Comment by TheUnable** [comment] 2018-10-25 16:47
It would be cool if u guys did remote fixes like being allowed to enter someones computer and seeing the issue itself...
ok im going to try this again step by step :) give me a sec

**Comment by TheUnable** [comment] 2018-10-25 16:52
after typing  
sudo tools/install.sh --update
then choosing 
kali
i get this error again my friends
E: Unable to locate package gir1.2-webkit-3.0
E: Couldn't find any package by glob 'gir1.2-webkit-3.0'
E: Couldn't find any package by regex 'gir1.2-webkit-3.0'
ERROR: Failed to install dependencies with apt-get

**Comment by wolfthefallen** [comment] 2018-10-25 17:10
please provide me the output of `cat /etc/debian_version`

**Comment by TheUnable** [comment] 2018-10-25 17:12
says stable

**Comment by wolfthefallen** [comment] 2018-10-25 17:13
please provide the whole out put of both files

**Comment by TheUnable** [comment] 2018-10-25 17:14
what do u mean? :(

**Comment by TheUnable** [comment] 2018-10-25 17:16
oh crap since my brother upgraded using parrot repos it went from kali to this now..
stable
Parrot 4.3 \n \l

**Comment by zeroSteiner** [comment] 2018-10-25 17:48
Should we close this issue if the resolution is to use a version of King Phisher that's supported?

**Comment by TheUnable** [comment] 2018-10-25 17:50
yes sir

**Closed** 2018-10-25 17:51 UTC
Labels: bug, help me, install
