### ISSUE TITLE
KingPhiser client 

### ISSUE THREAD

**Issue by seanjackson** [securestate/king-phisher#242] opened 2017-10-31 11:23 UTC
Failed To Connect To The King Phisher RPC Service
Ensure that the King Phisher Server is currently running.

WARNING  failed to connect to the remote rpc service
and this stack trace from the client's command line:

Traceback (most recent call last):
  File "/path/to/king-phisher/king_phisher/client/application.py", line
471, in server_connect
    server_version_info = rpc('version')
  File "/usr/local/lib/python2.7/dist-packages/AdvancedHTTPServer.py",
line 495, in __call__
    return self.call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/AdvancedHTTPServer.py",
line 546, in call
    resp = self.client.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

**Comment by zeroSteiner** [comment] 2017-10-31 12:24
It's important that you fill out the issue template in it's entirety. We need to other information such as when did this error occur, what OS are you using and most importantly, what version of King Phisher is being used.

Fill this out:
## Issue Description
I get a stack trace when I...

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 15.10 GNOME, Kali 2, etc.
King Phisher Version: x.y.z

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by seanjackson** [comment] 2017-10-31 13:06
everything is running just having problem with the client

**Comment by seanjackson** [comment] 2017-10-31 13:06
The client is not connecting

**Comment by zeroSteiner** [comment] 2017-10-31 13:07
That doesn't matter, we still need the information if we're going to be able to help.

**Comment by zeroSteiner** [comment] 2017-10-31 14:17
For clarity @seanjackson, please continue the conversation here.

**Comment by seanjackson** [comment] 2017-10-31 14:21
I am running Version 1.1.0, i have done everything configured the server_config.yml and the connection string.My problem is the client,whenever i try to connect with a Kingphisher client it does not connect

**Comment by seanjackson** [comment] 2017-10-31 14:22
Steiner i am using is preinstalled in kali linux

**Comment by zeroSteiner** [comment] 2017-10-31 14:24
Ok, yeah I understand that but please update to the latest stable version [v1.8.0](https://github.com/securestate/king-phisher/releases/tag/v1.8.0). We simply can't support versions that are a year and a half old. There have been plenty of bugs that have been fixed in that amount of time and we can't afford to duplicate efforts.

**Comment by wolfthefallen** [comment] 2017-10-31 14:39
If you are utilizing the newest version of Kali rolling you should just be able to do `apt install king-phisher` or `apt-get install --only-upgrade king-phisher`

**Comment by seanjackson** [comment] 2017-10-31 16:05
Okay.Stein and Wolf I want to ask another question.can you kindly tell me what do to when the KingPhisher client ask for ssh username and password.I seem lost in that aspect,secondly will I have to create a root user in the ssh config
Thank for your response.

**Comment by zeroSteiner** [comment] 2017-10-31 16:26
Please read through the FAQ question [What are the default credentials?](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#what-are-the-default-credentials) to answer your SSH username and password question.

**Comment by seanjackson** [comment] 2017-10-31 16:26
The Kinghisher Client keep triggering error that ensure the server is running.Cannot connect RPC services,with several references to third party HTTP server.

**Comment by seanjackson** [comment] 2017-10-31 16:33
Stein I have been troubleshooting this for the past 2 hours can't seem to get it

**Comment by seanjackson** [comment] 2017-10-31 16:37
I have inputted the  username and password,still having issues.Your expertise will be appreciated here
Thanks

**Comment by zeroSteiner** [comment] 2017-10-31 16:37
If the server is not running that would be a different error than if the credentials are incorrect. Do you know that the server is actively running as you're trying to log in? You can check with `systemctl status king-phisher`.

**Comment by wolfthefallen** [comment] 2017-10-31 17:06
@seanjackson The RPC failure to connect is normally due to king phisher not running on port 80 and/or 443. If you running a service on one of those ports you need to turn them off adjust the king phisher server's configuration back to run on 80 and/or 443. 

Please see FAQ:
[RPC Failure To Connect FAQ](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#king-phisher-client-fails-to-connect)

**Comment by seanjackson** [comment] 2017-10-31 18:35
Stein and wolf I have done all I can.The latest Kali Linux only support 2.7 seems Kingphisher is running on python 3.0+.

**Comment by seanjackson** [comment] 2017-10-31 18:41
I did everything,the latest kingphisher support 3.0 seems it's having hard time installing on kali Linux.

**Comment by zeroSteiner** [comment] 2017-10-31 18:42
No, that's not the case, you may need to upgrade your version of Kali however or you can install King Phisher from source. Either way you need to trouble shoot the client-server connection. If, however, you feel that you have in fact done all that you can, please close this issue to let us know that you have moved on.

If you choose to install from source, you'll still need to ensure that your version of Kali is recent. King Phisher will not work with Python 3.0, IIRC the minimum required version is actually 3.3.

**Comment by wolfthefallen** [comment] 2017-10-31 18:49
@seanjackson Looking through the screen shots you provided you are not running the most current version of Kali Linux. You are running a version from Jan 2016.. The most Current Version is [Kali Rolling 2017.2](https://www.kali.org/downloads/) Please upgrade to the latest version of Kali Linux.

**Comment by seanjackson** [comment] 2017-10-31 18:52
I am running the updated version of kali Linux.I updated yesterday

**Comment by zeroSteiner** [comment] 2017-10-31 19:02
@seanjackson what you're telling us and what you're showing us is conflicting information. Can you tell us what version of Kali you're running and how you came to that conclusion. And again, please provide more details in your responses so we can avoid this unnecessary back and forth.

**Comment by wolfthefallen** [comment] 2017-10-31 19:03
Your `uname -a` displays 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13)...` This tells me you have not done a full system upgrade in a long time. Do an `sudo apt update && sudo apt upgrade && sudo apt dist-upgrade` To upgrade to the latest version of Kali rolling. Once that is completed reboot your system do another `apt update && apt upgrade`.. reinstall king phisher through apt and see if the problem is still existing.

**Comment by seanjackson** [comment] 2017-10-31 19:23
Okay wolf thanks for the response.

**Comment by seanjackson** [comment] 2017-11-02 19:09
Hello guys thanks very much.When I updated to the recent kali Linux.The issue was gone.I am about to set up a campaign any problem I will contact you both.Thanks for the amazing response and support.

**Comment by zeroSteiner** [comment] 2017-11-02 19:15
Glad to hear it @seanjackson, going to close this out now.

**Closed by zeroSteiner** 2017-11-02 19:15 UTC
Labels: help me

**Comment by seanjackson** [comment] 2017-11-02 22:08
Please what is the web server URL
