### ISSUE TITLE
KingPhisher Clients Unresponsive

### ISSUE THREAD

**Issue by 0xIn7rud3r** [securestate/king-phisher#233] opened 2017-08-02 11:53 UTC
## Issue Description
KingPhisher Clients gets stuck forever on both linux and windows machines. Kingphisher Server is running on another machine, with client configured to use SSH over tunnel for sending mail

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS:  Kali 2,
KingPhisherServer Version: 1.7.1

## Error Details / Stack Trace
No Error, Just client become unresponsive. till force QUIT

![image](https://user-images.githubusercontent.com/30025517/28872487-1055a1e6-77a7-11e7-80fa-b3729555372b.png)

**Comment by zeroSteiner** [comment] 2017-08-02 12:21
Can you update to the latest version 1.8 and see if you can reproduce this issue. If you can reproduce it, please provide us with the [verbose output](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#how-do-i-generate-verbose-logging-output).

**Comment by 0xIn7rud3r** [comment] 2017-08-02 12:51
I tried with Updated Server i.e 1.8 and windows client and client becomes unresponsive as soon as send is clicked.

![image](https://user-images.githubusercontent.com/30025517/28874243-a474feec-77ae-11e7-82a2-fa05ec07e376.png)

**Comment by zeroSteiner** [comment] 2017-08-02 12:57
Ok please provide us with the logs from when you start it until it freezes. You can put them on pastebin or another service if you'd like. I'm expecting it may be a few hundred lines but it's important that we get that information.

Additionally, is the URL up? I'd expect the client may become unresponsive for a few seconds as it waits for the request to complete but no more than maybe 30 seconds or so.

**Comment by 0xIn7rud3r** [comment] 2017-08-02 20:53
I reconfigured all from scratch, everything seems to be working fine now. i'll update with logs if i am able to reproduce it again.

**Comment by 0xIn7rud3r** [comment] 2017-08-03 09:55
So Client becomes unresponsive as soon as start is clicked. 
Running KP server on another host then client.
Client is configured to use SMTP over SSH channel.

Few points i noticed.

No pop for ssh login after clicking Start in send tab. client becomes unresponsive.
Also getting into not responding state when clicking check SPF.
![image](https://user-images.githubusercontent.com/30025517/28916421-ca85c57e-785f-11e7-96aa-9dac46a1dd59.png)


Note: URL is up and running fine. SPF records are also file as i was able to send some mails earlier. now its getting stuck for same client config.

[debug_log.txt](https://github.com/securestate/king-phisher/files/1196760/debug_log.txt)

**Comment by zeroSteiner** [comment] 2017-08-03 12:20
It looks like the logs you provided are for the server but the issue appears to be in the client. Can you please provide the logging output for the client?

**Comment by 0xIn7rud3r** [comment] 2017-08-04 06:09
Not sure where i can get the client verbose logs in windows. -L switch doesn't seem to work here with win binary.

**Comment by zeroSteiner** [comment] 2017-08-04 11:05
You'll have to get them from a Linux install.

**Comment by wolfthefallen** [comment] 2017-08-07 17:20
I have been unable to reproduce this issue with the windows client. 
I would recommend checking your SMTP server logs and see if there is an issue there.

**Comment by 0xIn7rud3r** [comment] 2017-08-08 10:58
I found what was causing the issue. in my case it is DNS server, primary DNS server was not responding while client was trying to resolve TXT record for domain. 

Attached are client logs from application start to unresponsive stage.

[debug_log.txt](https://github.com/securestate/king-phisher/files/1207761/debug_log.txt)

PS: Just not sure why client didnt tried resolving from secondary name server record.

**Comment by zeroSteiner** [comment] 2017-08-14 13:01
This issue has now been fixed in the dev branch. To obtain the changes, you can either wait for them to be merged into the master branch (which will likely take a few weeks) or you can obtain them immediately by opting into [beta testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).

**Closed by zeroSteiner** 2017-08-14 13:01 UTC
Labels: can't reproduce
