### ISSUE TITLE
Openssl.error

### ISSUE THREAD

**Issue by paragkamra** [securestate/king-phisher#212] opened 2017-05-04 12:45 UTC
i am using it for cloudworksms. my kingphisher client is on windows 10 with python2.7 when i start sending the sms i am getting this error.

#ISSUE WITH OPNSSL
Error Type: OpenSSL.SSL.Error
Error Details: Error([('system library', 'fopen', 'No such process'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')],)
Error UID: 854713ef-eeb6-471c-9690-9d546f9a16e0
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.7.0
Platform Version: Windows: 10 10.0.14393  Multiprocessor Free (Frozen=True)
Python Version: 2.7.12
Gtk Version: 3.14.15
Timezone: Asia/Calcutta

Thread Information:
 => MainThread (alive=True daemon=False)
    Thread-6 (alive=True daemon=True)
    Thread-1 (alive=True daemon=False)
    Thread-2 (alive=True daemon=True)
    Thread-7 (alive=True daemon=True)

Stack Trace:
Traceback (most recent call last):
  File "C:\Program Files (x86)\KingPhisher\king_phisher\plugins\clockwork_sms.py", line 51, in signal_send_precheck
    resp = self._get_balance()
  File "C:\Program Files (x86)\KingPhisher\king_phisher\plugins\clockwork_sms.py", line 35, in _get_balance
    resp = requests.get('https://api.clockworksms.com/http/balance?key=' + api_key)
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 411, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "C:\Python27\lib\site-packages\OpenSSL\SSL.py", line 533, in load_verify_locations
  File "C:\Python27\lib\site-packages\OpenSSL\_util.py", line 48, in exception_from_error_queue
Error: [('system library', 'fopen', 'No such process'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]

![2017-05-04 18_14_45-king phisher](https://cloud.githubusercontent.com/assets/28391895/25704056/a620ecf6-30f5-11e7-83f3-da953f400737.png)

**Comment by zeroSteiner** [comment] 2017-05-04 12:48
Thanks for the bug report! I'm pretty confident that this is a duplicate of #204 which has already been fixed. Please update to version [1.7.1](https://github.com/securestate/king-phisher/releases/tag/v1.7.1) and the issue should be resolved.

**Comment by paragkamra** [comment] 2017-05-04 12:55
ok 👍 will try with 1.7.1

**Closed** 2017-05-08 06:05 UTC
Labels: bug, duplicate
