### ISSUE TITLE
server_config.yml configuration error

### ISSUE THREAD

**Issue by justin89** [securestate/king-phisher#45] opened 2015-10-21 09:19 UTC
Hello,
I'm having the error down below. I couldn't figue it out.Could you help me?
when I type this ;
/opt/king-phisher/KingPhisherServer -L INFO /opt/king-phisher/server_config.yml

I get the following error;
an error occured while parsing the server configuration file while parsing a block mapping in "/opt/king-phisher/server_config.yml", line 5, column 1
expected 'block end ', but found ' block mapping start' in "/opt/king-phisher/server_config.yml" ,line 40, column 3

my server_config.yml looks like;

there is 3 line of comment and then 1 blank line after blank line it starts with;
logging:
  file: /var/log/king-phisher.log
  level: warning
  console: false

server:
  # Bind address information
  address:
    host: 0.0.0.0
    port: 80

  # Authentication related information
  #authentication:
    # Require authenticating users to be a member of the specified group
    #group: king-phisher

  # A cookie to retrieve the client's IP from, useful when a proxy is in place
  #client_ip_cookie: X-Real-IP

  # The name of the cookie used to track users
  cookie_name: KPID

  # Specify an additional search path for server data files
  #data_path: /opt/king-phisher/data/server

  # The SQLite3 database file to use, the folder needs write permissions
  # WARNING: SQLite3 is not fully supported as of version 0.1.6, see
  # https://github.com/securestate/king-phisher/wiki/Database#sqlite for more
  # details
  #database: sqlite:////var/king-phisher/king-phisher.db
  database: postgresql://user:pass@localhost/king_phisher <<<<<<user and pass is secret :))>>>>>>>
  # The Postgres database to use
  #database: postgresql://user:pass@localhost/king_phisher

  # Fork the server process into the background
  fork: true

  geoip:
    # The location of the GeoLite2 City database
    database: /var/king-phisher/geoip.mmdb

  # Set a file to write the PID to
  pid_file: /var/run/king-phisher.pid

  # Require an ID associated with a campaign to load pages
  require_id: true

  rest_api:
    enabled: false
    # Networks which are authorized to use the REST API
    networks:
      - 10.0.0.0/8
      - 127.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
    # When null the token will be randomized at run time
    token: null

  # Configure the server header value
  #server_header: Apache/2.4.9 (Unix)

  # Set the opened timestamp on the first visit if it's null
  set_message_opened_on_visit: true

  # Drop privileges to the specified user
  setuid_username: nobody

  # SSL settings
  #ssl_cert: /path/to/ssl.crt
  #ssl_key: /path/to/ssl.key

  # Configure the image file name used to track opened emails
  tracking_image: email_logo_banner.gif

  # Use subfolders in the web_root which correspond to vhost names
  vhost_directories: false
  web_root: /var/www

Anybody knows why I'm getting this error ?

**Comment by zeroSteiner** [comment] 2015-10-21 12:30
By commenting out the database line you specified and using the sqlite one I was able to get this configuration to load. That looks like a YAML parsing error, so I would start by double checking the configuration is valid. You can check if the problem is being introduced by the postgresql database connection string by commenting it out and seeing if the server will start with sqlite.

**Comment by zeroSteiner** [comment] 2015-10-29 14:27
This issue hasn't been updated in a week so I'm going to close it out. If you're still experiencing the same issue just follow up on this thread.

**Closed by zeroSteiner** 2015-10-29 14:27 UTC
