### ISSUE TITLE
Errors while running tests with python3

### ISSUE THREAD

**Issue by sbrun** [securestate/king-phisher#149] opened 2016-08-30 13:01 UTC
## Issue Description
I'm working on updating the kali package to the latest version (1.4.0).
I started to work with python2 and everything was OK, tests ran successfully and I was able to start king phisher without problem.
As you recommend to use Python3, I tried to build the package and to run the tests with python3. Now 2 tests failed.

## Environment Details
Kali-rolling
There is no difference between the build in Python2 and the one in Python3 except that I dropped ipaddress module for Python3.
I can't use dnspython3, I'm using the package python3-dnspython (version 1.14.0-3 which is in kali-rolling). The version 1.14 of dnspython is for python2 and python3.

## Error Details / Stack Trace
```
======================================================================
ERROR: test_campaign_workflow (tests.server.server.CampaignWorkflowTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/server/server.py", line 190, in test_campaign_workflow
    step()
  File "/<<PKGBUILDDIR>>/tests/server/server.py", line 126, in step_3_get_visits
    visit_count = self.rpc('db/table/count', 'visits', query_filter={'campaign_id': self.campaign_id})
  File "/usr/lib/python3/dist-packages/advancedhttpserver.py", line 514, in __call__
    return self.call(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/advancedhttpserver.py", line 572, in call
    raise RPCError('remote method incurred an exception', resp.status, remote_exception=resp_data['exception'])
advancedhttpserver.RPCError: a remote exception occurred

======================================================================
ERROR: test_spf_check_host (tests.spf.SPFTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/king_phisher/testing.py", line 105, in decorated
    return test_method(self, *args, **kwargs)
  File "/<<PKGBUILDDIR>>/tests/spf.py", line 42, in test_spf_check_host
    check_host_result = s.check_host()
  File "/<<PKGBUILDDIR>>/king_phisher/spf.py", line 170, in check_host
    self.policy = self._check_host(self.ip_address, self.domain, self.sender)
  File "/<<PKGBUILDDIR>>/king_phisher/spf.py", line 183, in _check_host
    answers = [answer for answer in answers if answer.strings[0].startswith('v=spf1 ')]
  File "/<<PKGBUILDDIR>>/king_phisher/spf.py", line 183, in <listcomp>
    answers = [answer for answer in answers if answer.strings[0].startswith('v=spf1 ')]
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by wolfthefallen** [comment] 2016-09-02 13:14
@sbrun Thank you bringing this to our attention. So we can make sure we are building the testing environment correctly to meet the requirements for kali, can you please provide me a list of what requirements are installed via apt, and what packages are installed via pip3. 

This will greatly speed up the process to make sure we are working with in the packages for Kali rolling.

**Comment by sbrun** [comment] 2016-09-02 14:44
I don't use pip3, only kali packages installed via apt.

Here is the list of packages for the build:
python3, python3-alembic, python3-advancedhttpserver, python3-blinker, 
python3-boltons, python3-dnspython, python3-geoip2, python3-geojson,
python3-icalendar, python3-jinja2, python3-markupsafe, python3-matplotlib, 
python3-msgpack, python3-pampy, python3-paramiko, python3-pluginbase,
python3-psycopg2, python3-pyotp, python3-dateutil, python3-tz,
python3-yaml, python3-requests, python3-six, python3-smoke-zephyr,
python3-sqlalchemy, python3-termcolor, python3-tzlocal,
python3-xlsxwriter, python3-gi, python3-gi-cairo, gir1.2-vte-2.91,
gir1.2-gtksource-3.0, gir1.2-webkit2-4.0, debhelper, dh-systemd, xvfb,
xauth

You can also find the informations in the git repo of the package (I prepare the package for python3):
http://git.kali.org/gitweb/?p=packages/king-phisher.git;a=summary

You can find the list of packages used for the build and for the installation in the debian/control file.

Let me know if you need something else.
Thanks for your help

**Comment by zeroSteiner** [comment] 2016-09-02 15:14
I'm able to reproduce this error. It looks like `dnspython3` is no longer supported and the primary `dnspython` package now supports both Python 2.x and Python 3.x (previous versions did not). We'll need to update our code base to use the `dnspython==1.14` package and drop the old one for Python 3. The changes should be pretty straight forward and I'll make sure this ticket is updated with our progress.

**Comment by zeroSteiner** [comment] 2016-09-03 03:22
Commit ab14936fffe55d3b6569e27b5862e72df75295e8 updates the `dnspython` package as I previously mentioned would be required. We'll need to get it merged over and into the master branch before it will be compatible with Kali's packaged version.

**Comment by zeroSteiner** [comment] 2016-09-12 13:08
@sbrun Thanks for your patience on this. We pushed over the changes from the dev branch into master this morning meaning the necessary updates to use the `dnspython==1.14` package instead of the old `dnspython3` one are now incorporated. The unit tests should pass now.

The latest commit with these changes is ab14936fffe55d3b6569e27b5862e72df75295e8 (now in the master branch).

**Comment by naveenperala** [comment] 2016-09-22 20:38
I Did use uninstall.sh script and tried a fresh installation as I thought something might  be wrong with installation.

Seems I got the same error as above:

king#pwd
/opt/king-phisher
king#systemctl status king-phisher.service
● king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2016-09-22 20:31:41 UTC; 15s ago
  Process: 65391 ExecStart=/usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.yml (code=exited, status=78)

Sep 22 20:31:39 app01 systemd[1]: Starting King Phisher Server...
Sep 22 20:31:41 app01 python3[65391]: [-] an error occurred while parsing the server configuration file
Sep 22 20:31:41 sapp01 python3[65391]: [-] did not find expected <document start>
Sep 22 20:31:41 app01 python3[65391]: [-]   in "/opt/king-phisher/server_config.yml", line 5, column 1
Sep 22 20:31:41 app01 systemd[1]: king-phisher.service: Control process exited, code=exited status=78
Sep 22 20:31:41 app01 systemd[1]: Failed to start King Phisher Server.
Sep 22 20:31:41 app01 systemd[1]: king-phisher.service: Unit entered failed state.
Sep 22 20:31:41 app01 systemd[1]: king-phisher.service: Failed with result 'exit-code'.
king#


please find my yml file as an attachment and kindly let me where did we went wrong.
[server_config.yml.txt](https://github.com/securestate/king-phisher/files/488324/server_config.yml.txt)

**Comment by zeroSteiner** [comment] 2016-09-22 20:44
If you read the error message it says the problem is with line 5. Also your configuration file contains your Postgresql password so please stop posting it. The file as uploaded is malformed. It looks like you copied and pasted it from the console output including the cat command. 

Because this is not a bug in King Phisher, I'm going to close this issue out. Fix your configuration file and postgresql credentials.

**Comment by wolfthefallen** [comment] 2016-09-22 20:50
Version 1.5.0 final has been released in Master. This version on King Phisher has the commit to support `dnspython` in python3.

**Closed by wolfthefallen** 2016-09-22 20:50 UTC
Labels: in progress
