### ISSUE TITLE
Problem with non-standard characters in website templates

### ISSUE THREAD

**Issue by twkrol** [securestate/king-phisher#168] opened 2016-11-07 12:06 UTC
## Issue Description
I get a resulting web page served by king phisher cut by X characters, when I use X utf characters in my html template contents. For example I do use Polish characters eg: ąćęłńóśżź and their capitals.

## Reproduction Steps
1. Copy standard web template file
2. In the body, somewhere add 7 characters like ąćęłńóś
3. Put this file on your king phisher host web directory
3. Load this file on your browser via host's url (must be served by king phisher server)
4. Check page source, the last 7 characters (in this case the whole "</html>" tag) disappears.

## Environment Details

Host OS: Ubuntu 16.04.1 LTS

## Error Details / Stack Trace

```
No errors found at the server, just client side
```

**Comment by zeroSteiner** [comment] 2016-11-07 12:50
What version of King Phisher are you using?

**Comment by zeroSteiner** [comment] 2016-11-07 13:25
Is the file encoded in UTF-8 and what is the error message in the server logs?

**Comment by twkrol** [comment] 2016-11-07 13:35
Yes, the file is UTF-8 encoded and there is no message in server log.
Attaching example file.
[sorry.txt](https://github.com/securestate/king-phisher/files/575445/sorry.txt)

**Comment by twkrol** [comment] 2016-11-07 13:51
Update: file above is with my workaround: several spaces at the end, which prevents html content to be stripped.
Real example problematic file included here, just plain html ended with </html>, which gets stripped. 
(please rename to "sorry" without .txt)
[sorry.txt](https://github.com/securestate/king-phisher/files/575479/sorry.txt)

**Comment by zeroSteiner** [comment] 2016-11-07 16:45
This is definitely a bug. The issue is that when the `Content-Length` header is calculated, it's calculated based on the size of the string type in Python instead of the bytes type which is what is actually sent to the client. I should be able to get this issue patched soon. Thanks for bringing this to our attention.

**Comment by zeroSteiner** [comment] 2016-11-07 17:10
This issue has now been fixed in the dev branch. To obtain the changes, you can either wait for them to be merged into the master branch (which will likely take a few weeks) or you can obtain them immediately by opting into [beta testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).

See commit 61323669fd1f3c7e8da83dba632bd87db4937a60.

**Closed** 2016-11-07 17:10 UTC
Labels: bug

**Comment by twkrol** [comment] 2016-11-07 23:51
Thank you - you helped many non-english users 👍
