### ISSUE TITLE
king phisher does not work with non standard SSH ports.

### ISSUE THREAD

**Issue by thesle3p** [securestate/king-phisher#53] opened 2015-12-08 22:56 UTC
Hi, It looks like the  King Phisher client can not communicate with non standard ssh ports (other then 22) I have tried modifying the king-phisher/king_phisher/ssh_forward.py module to point to the correct port  but it looks like paramiko will not connect to SSH on any other port then 22.

**Comment by zeroSteiner** [comment] 2015-12-08 23:07
I assure you that it does without any code modifications. In the client
connection dialog just set the server to 1.2.3.4:987 where 987 is the SSH
port on the King Phisher server. Leave HTTP at 80 or 443 or what it's
configured for in the server config file.

**Comment by thesle3p** [comment] 2015-12-08 23:08
I spent half of today doing that and it did not work......

**Comment by zeroSteiner** [comment] 2015-12-08 23:13
What error message are you receiving and do you permit tcp port forwarding
with your SSH service configuration?

**Comment by zeroSteiner** [comment] 2015-12-08 23:14
Also posting debug output from the console for the client would be helpful
in trouble shooting this.

**Comment by zeroSteiner** [comment] 2015-12-14 15:43
Any update on this issue? I'd like to help but require more information in order to do so.

**Comment by zeroSteiner** [comment] 2015-12-16 13:48
If you're still running into this issue feel free to comment on this thread with additional details. Until then since I can't reproduce this problem, I'm going to close it.

**Closed by zeroSteiner** 2015-12-16 13:48 UTC
Labels: can't reproduce
