### ISSUE TITLE
Denied access to server

### ISSUE THREAD

**Issue by riveta** [securestate/king-phisher#89] opened 2016-03-30 06:31 UTC
Hi, 

The web server URL sent via the phishing email to a target shows a 404 error when accessed.
I see a corresponding warning message on the server interface: "denying request with not found due to invalid hostname". However, I am able to verify the web server URL from the client application.

I did not face this issue until last week; it seems to have cropped up only now. Please help.

Thank you

**Comment by zeroSteiner** [comment] 2016-03-30 12:52
I'm guessing that you have the `require_id` setting enabled in the servers configuration. Can you please confirm this? Also do you have the setting `vhost_directories` set to true or false?

What appears to be happening is the landing page can not be found for the request. This is could be due to a naming error in the directory of the web root if `vhost_directories` is enabled. Something else that would be helpful for trouble shooting would be if you could post a contents of the `web_root` via `ls`.

**Comment by riveta** [comment] 2016-03-31 05:05
Yes i have enabled `require_id` settings  in the server configuration, but I still cannot access the server using the ID generated while sending the URL in the mail to the target, though I can access the page using the ID generated when I click 'Verify URL'.

Also, I have set `vhost_directories` to false.

I am attaching the screenshot of `web_root` via `ls`

![screenshot from 2016-03-31 09-50-46](https://cloud.githubusercontent.com/assets/7737344/14165924/0d3031b8-f72c-11e5-9bad-667d55e09de0.png)

**Comment by zeroSteiner** [comment] 2016-03-31 13:09
When you're visiting the page are you using the same hostname / URL that was sent in the email? When an email is sent the landing page is communicated to the server and stored. It's looking like the server is rejecting your request because ti does not look like it's for a known landing page.

This could for example be caused by using a hostname in the target url field, sending an email and then hitting the server with the valid id but an IP address instead of the hostname.

If you're still having trouble can you turn on debug logging on the server and post the lines around when you request the page? That would give me some more insight as to what might be happening.

**Comment by d4rk140r** [comment] 2016-04-05 00:02
Hello, do you have any tutorial to use this tool? Really i would like implement this campaing on my company (i am the CISO). Thanks a lot for your support.

**Comment by zeroSteiner** [comment] 2016-04-05 00:25
@d4rk140r yes we have a variety of resources and tutorials including new videos all of which can be found in the project's wiki page.

**Comment by riveta** [comment] 2016-04-05 07:05
I am sending the server IP address and port number as the URL in the mail. I am attaching the screen shots of the issue faced:

1. The web server URL is verified using the client application
![1](https://cloud.githubusercontent.com/assets/7737344/14273730/581ddfb6-fb2a-11e5-9526-5e494d59971a.png)
2. The server log (in debug mode) the Verify URL is getting 200 OK status 
![2](https://cloud.githubusercontent.com/assets/7737344/14273737/60079992-fb2a-11e5-8667-9c1bcb77a362.png)
3. ID generated when sending mail (OTFWFkgB4l8zr1h7)
![3](https://cloud.githubusercontent.com/assets/7737344/14273743/6619d7aa-fb2a-11e5-8282-6683ffe12e1c.png)
4. Failed access the URL with ID generated during sending mail
![4](https://cloud.githubusercontent.com/assets/7737344/14273748/75d9eea0-fb2a-11e5-943d-b8e837b1ec86.PNG)
5. Server Log of the URLs accessed 
![5](https://cloud.githubusercontent.com/assets/7737344/14273752/7a0e7fae-fb2a-11e5-890b-844f401c229d.png)
6. Accessing server with ID generated during Verify URL
![6](https://cloud.githubusercontent.com/assets/7737344/14273755/801d3b38-fb2a-11e5-811b-df1c5499520b.png)
7. Accessing server with ID generated during sending mail 
![7](https://cloud.githubusercontent.com/assets/7737344/14273766/94c88b32-fb2a-11e5-8141-bc5c5a178fd6.png)
8. Server Log
![8](https://cloud.githubusercontent.com/assets/7737344/14273769/9907a336-fb2a-11e5-85a9-2e6f88861e15.png)

**Comment by zeroSteiner** [comment] 2016-04-05 12:33
Ok, I was able to reproduce this. There's a problem with how the vhost is used to verify the legitimacy of a landing page when a non-default port is in use.

**Comment by zeroSteiner** [comment] 2016-04-05 12:52
This issue has now been fixed in commit 079b53f7 which is in the dev branch.

You can either update your version of King Phisher to 1.3.0-beta, wait for it to be released to Kali (which may be quite a while), use a default port (like 80) or finally your last option is to simply disable the require_id setting for now. If you opt to update, there are instructions in the [wiki](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).

Thanks for your patience on this, I'm glad we were able to identify the issue.

**Comment by zeroSteiner** [comment] 2016-04-10 19:39
I'm going to close this issue since it's been fixed and there hasn't been a response. If you're still having trouble with it just comment on this thread.

**Closed by zeroSteiner** 2016-04-10 19:39 UTC
Labels: bug

**Comment by riveta** [comment] 2016-04-12 06:20
Sorry for the delayed response, I have disabled require_id option and I am able to view the landing page. Now I am facing another issue with harvesting credentials but both `Messages` and `Visits` tabs details are properly enumerated.
