### ISSUE TITLE
King Phisher support for URL shorteners

### ISSUE THREAD

**Issue by jasdwr1** [securestate/king-phisher#107] opened 2016-04-26 15:35 UTC
## Issue Description
When I use a shortened URL, bit.do in this case, the client can resolve the web page prior to sending the email but when the email is delivered the tracking_dot_image_tag is the black X denoting it cannot be resolved, therefore I cannot track who opened the email.  Change the Web Server URL to my true domain name and it works like a champ.

From the email I can click on the link that resolves to the shortened URL and access the web page.

We're still running version 0.20 (ahem) and I didn't see anything about URL shorteners in the release notes.

## Reproduction Steps
1. Use a URL shortener (bit.do and it.gd attempted)
2. Use shortened URL in the Web Server URL and verify successfully
3. Submit campaign - no errors
4. Look at email, tracking_dot_image_tag is a black X

## Environment Details
Host OS: Fedor 20, King Phisher 0.20 Postgres

## Error Details / Stack Trace

```
 
```
Message HTML:
![message html](https://cloud.githubusercontent.com/assets/18683145/14824104/bf4f9e76-0ba2-11e6-9f29-d59283e65125.JPG)

Email with original URL:
![with original url](https://cloud.githubusercontent.com/assets/18683145/14824105/bf50ce36-0ba2-11e6-9dc6-173975497b4c.JPG)

Email with shortened email
![with shortened url](https://cloud.githubusercontent.com/assets/18683145/14824106/bf54d404-0ba2-11e6-9257-4256f77f69cb.JPG)

**Comment by zeroSteiner** [comment] 2016-04-26 15:45
Couple of thoughts on this. I highly recommend upgrading, alot of improvements and bug fixes have been made since v0.2 was released about 10 months ago.

Setting the webserver URL to something other than the King Phisher server itself will break how the landing pages are tracked since the resource of the URL is recorded by the server. What I would recommend you do is set the webserver URL correctly in the GUI and then use Jinja in your template to set the short url or just insert it into the HTML directly.

Something like this should help:
```html
<html>
{% set short_url = 'http://bit.ly/something' %}
Hello!
<a href="{{ short_url }}?id={{ uid }}">Click Here</a>
<br />
{{ tracking_dot_image_tag }}
</html>
```

Also be aware that if the URL shortener is not forwarding the `id` parameter, then your visits won't be tracked at all. Alternatively if you set the `id` parameter when creating the short URL all of the visits will be attributed to the same target. I don't know if the shortener service will forward the parameters so you'll definitely want to test that.

**Comment by jasdwr1** [comment] 2016-04-26 16:36
Thanks zS, the code worked, I am able to see when the email was opened.  The UID is part of the link and when I click on it, the unshortened URL with the ?id= is in the browser address bar, but it isn't showing up in the campaign visits list.  Seems like they are hit-and-miss, probably some of the fixes/improvements, I've used my true domain, an alternate domain and the shortened (bit.ly as well as bit.do).  I have one with the primary domain and one with the bit.ly in the visited list.

**Comment by zeroSteiner** [comment] 2016-04-26 16:39
Did you resend an email with that configuration? Under the hood, when a message is sent, King Phisher inspects the Web Server URL and uses the resource as a landing page. This landing page set in the URL needs to be the one that the shortened link is directing to along with the `id` parameter in order for the visit to be logged. If the shortened link is redirecting to a page that's different that the one that was in the Web Server URL at the time the message was sent, or the `id` parameter is missing, the visit wont be logged.

**Comment by jasdwr1** [comment] 2016-04-26 18:19
That makes sense, I'm still missing something and I'm sure it is super basic.  Created a brand new campaign - of course the values carried forward.  I started simple, the real URL of the KP server and the link HREF as url.webserver.  I see the message is opened but no visits.  Same for the alternate name, a new campaign, used the alternate name for the KP server; nothing in the visits.  Still plugging.

If you want, close this thread as what you supplied works with the caveat that the URL shortener must pass the id=; unless you have that d'oh solution to me not seeing visit.

As always, tons of thanks for the help.

**Comment by zeroSteiner** [comment] 2016-04-26 19:57
I'll close this out. I'm not sure what the issue is regarding the visits but I hope you're able to figure it out. I would also recommend looking through the server logs to see if it's complaining about any invalid IDs, hostnames etc.

**Closed by zeroSteiner** 2016-04-26 19:57 UTC
