### ISSUE TITLE
Client start error

### ISSUE THREAD

**Issue by bobscaggs** [securestate/king-phisher#329] opened 2018-10-22 20:30 UTC
## Issue Description
I experience an issue when I start the client and the results I expected are startup of client

## Reproduction Steps
1. Start King Phisher
2. Error below presented

## Environment Details

Host OS: 4.17.0-kali1-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux
King Phisher Version:1.11.0

## Error Details / Stack Trace
~# /opt/king-phisher/KingPhisher
Traceback (most recent call last):
  File "/opt/king-phisher/KingPhisher", line 48, in <module>
    from king_phisher.client import application
  File "/opt/king-phisher/king_phisher/client/application.py", line 56, in <module>
    from king_phisher.client import dialogs
  File "/opt/king-phisher/king_phisher/client/dialogs/__init__.py", line 35, in <module>
    from .clone_page import *
  File "/opt/king-phisher/king_phisher/client/dialogs/clone_page.py", line 37, in <module>
    from king_phisher.client.widget import extras
  File "/opt/king-phisher/king_phisher/client/widget/extras.py", line 46, in <module>
    import mdx_partial_gfm
  File "/usr/local/lib/python3.6/dist-packages/mdx_partial_gfm/__init__.py", line 33, in <module>
    import gfm
  File "/usr/local/lib/python3.6/dist-packages/gfm/__init__.py", line 15, in <module>
    from gfm import spaced_link
  File "/usr/local/lib/python3.6/dist-packages/gfm/spaced_link.py", line 38, in <module>
    BRK = markdown.inlinepatterns.BRK
AttributeError: module 'markdown.inlinepatterns' has no attribute 'BRK'

**Comment by zeroSteiner** [comment] 2018-10-22 20:36
This looks like a duplicate of #324 and has already been fixed in master and dev. Go ahead and update your version of King Phisher.

When you run `./KingPhisher --version` it should say `KingPhisher Version: 1.12.0-beta ...`.

There's instructions in the [wiki](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#version-111-and-below) on how to upgrade. 1.12.0 isn't out yet so follow the instructions for 1.11 and below.

**Comment by zeroSteiner** [comment] 2018-10-23 12:43
Since this is a duplicate, I'm going to close this out. If you're still experiencing issues after updating just let us know.

**Closed by zeroSteiner** 2018-10-23 12:43 UTC
Labels: bug, duplicate

**Comment by bobscaggs** [comment] 2018-10-23 13:18
Upgrade fixed the issue.  Thanks!!!!
