### ISSUE TITLE
An unhandled exception has ocurred.

### ISSUE THREAD

**Issue by d4rk140r** [securestate/king-phisher#95] opened 2016-04-05 14:23 UTC
## Issue Description
I get a stack trace when I startt the client. 

## Reproduction Steps
1. Start King Phisher Server
2. Start King Phisher Client 
3. Login with my Credentials, and start connection with server OK.
4. Few seconds later, appears this :
![screenshot from 2016-04-05 10-17-24](https://cloud.githubusercontent.com/assets/17787065/14285060/13326294-fb18-11e5-9b13-db48767e766e.png)

## Error Details / Stack Trace
```
Copy details from the logs or client dialog here.
daemon=False)

Stack Trace:
Traceback (most recent call last):
  File "/usr/share/king-phisher/king_phisher/client/tabs/campaign.py", line 393, in loader_idle_routine
    self.logger.debug('idle loader routine called')
  File "/usr/lib/python2.7/logging/__init__.py", line 1147, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1277, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1251, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 285, in __init__
    self.threadName = threading.current_thread().name
  File "/usr/lib/python2.7/threading.py", line 1151, in currentThread
    return _active[_get_ident()]
TypeError: Couldn't find foreign struct converter for 'cairo.Context'


```

**Comment by zeroSteiner** [comment] 2016-04-05 14:29
This looks to me like a duplicate of a bug we filed with the Kali project on their [bug tracker](https://bugs.kali.org/view.php?id=3054). It also looks like you're using v1.1.0 which is out of date. Can you please verify that you're using the latest version provided by Kali?

Updating would be the ideal fix, otherwise you can work around the issue by manually installing `python-gi-cairo` and restarting the client.

**Comment by d4rk140r** [comment] 2016-04-05 16:03
apt-get update && apt-get upgrade .....and problem SOLVED!!! Thanks a lot for your support.

**Closed** 2016-04-05 16:04 UTC
Labels: bug, duplicate
