### ISSUE TITLE
Invalid version number when trying to run KingPhisherServer on Kali Linux

### ISSUE THREAD

**Issue by silasbarnes** [securestate/king-phisher#16] opened 2015-03-27 04:14 UTC
uname -a = Linux shad0wlyte 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux

When attempting to run KingPhisherServer, the following error occurs: 

...
root@shad0wlyte:/opt# sudo /opt/king-phisher/KingPhisherServer -L INFO -f /opt/king-phisher/server_config.yml
Traceback (most recent call last):
  File "/opt/king-phisher/KingPhisherServer", line 211, in <module>
    sys.exit(main())
  File "/opt/king-phisher/KingPhisherServer", line 85, in main
    missing_requirements = check_requirements(__requirements__)
  File "/usr/local/lib/python2.7/dist-packages/smoke_zephyr/requirements.py", line 85, in check_requirements
    installed_version = distutils.version.StrictVersion(installed_pkg.version)
  File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '0.7.5.post2'
root@shad0wlyte:/opt# 
...

Installed using "wget -q https://github.com/securestate/king-phisher/raw/master/tools/install.sh && sudo bash ./install.sh". about an hour ago which also appeared to experience errors:

...
Linux version detected as Kali
Downloading and installing the King Phisher server to /opt/king-phisher
Installing Kali dependencies
install.sh: 101: [: Kali: unexpected operator
install.sh: 108: [: Kali: unexpected operator
install.sh: 119: [: Kali: unexpected operator
install.sh: 131: [: Kali: unexpected operator
Installing Python package dependencies from pypi
Requirement already satisfied (use --upgrade to upgrade): six>=1.7.0 in /usr/lib/python2.7/dist-packages
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): alembic>=0.6.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): dnspython>=1.12.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): geoip2>=2.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.7.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): markupsafe>=0.18 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): matplotlib>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): msgpack-python>=0.4.2 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): paramiko>=1.10.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): psycopg2>=2.5.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): py2-ipaddress==2.0.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): smoke-zephyr==1.0.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): SQLAlchemy>=0.9 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): Mako in /usr/local/lib/python2.7/dist-packages (from alembic>=0.6.7->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): requests>=2.4 in /usr/local/lib/python2.7/dist-packages (from geoip2>=2.1.0->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): maxminddb>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from geoip2>=2.1.0->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6 in /usr/lib/pymodules/python2.7 (from matplotlib>=1.4.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /usr/lib/python2.7/dist-packages (from matplotlib>=1.4.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/dist-packages (from matplotlib>=1.4.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/lib/python2.7/dist-packages (from matplotlib>=1.4.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): pyparsing!=2.0.0,>=1.5.6 in /usr/lib/python2.7/dist-packages (from matplotlib>=1.4.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): nose>=0.11.1 in /usr/lib/python2.7/dist-packages (from matplotlib>=1.4.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): mock in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.4.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): pycrypto!=2.4,>=2.1 in /usr/lib/python2.7/dist-packages (from paramiko>=1.10.1->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.11 in /usr/local/lib/python2.7/dist-packages (from paramiko>=1.10.1->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): ipaddr in /usr/local/lib/python2.7/dist-packages (from maxminddb>=1.1.0->geoip2>=2.1.0->-r requirements.txt (line 5))
Cleaning up...
Installing the client desktop application file
Updating the GTK icon cache
gtk-update-icon-cache: Cache file created successfully.
install.sh: 199: [: Kali: unexpected operator
Start the King Phisher server with the following command: 
sudo /opt/king-phisher/KingPhisherServer -L INFO -f /opt/king-phisher/server_config.yml
...

Manually installed the Kali packages referenced in install.sh. No dice.

**Comment by zeroSteiner** [comment] 2015-03-27 19:32
I was able to reproduce this error. I should have a chance to look at fixing it this weekend. Seems to stem from a package with a non-standard version identifier of ```0.7.5.post2```.

**Comment by silasbarnes** [comment] 2015-03-27 19:51
You rock. Thanks mate.

Silas

**Comment by zeroSteiner** [comment] 2015-03-27 20:58
Found the offending package. The latest version of ```alembic``` is using the invalid format of ```0.7.5.post2``` .While this is an issue I will fix, you can temporarily work around the issue by explicitly installing a version of alembic that uses a valid version number.

Running ```pip install alembic==0.6.7``` should fix the problem for now until I get a permanent fix tested and pushed up.

**Comment by silasbarnes** [comment] 2015-03-27 23:23
Ran 'pip install alembic==0.6.7' after removing /opt/king-phisher/ and ran the automated installer again. Works a treat, thanks again mate.

Silas

**Comment by zeroSteiner** [comment] 2015-03-28 00:04
Fantastic, glad it's working now. I'm going to close this now because a permanent fix is now available in the master branch.

**Closed by zeroSteiner** 2015-03-28 00:04 UTC
Labels: bug
