### ISSUE TITLE
Can't Export Campaign XML in Version 1.12.0

### ISSUE THREAD

**Issue by scandox** [securestate/king-phisher#336] opened 2018-11-22 16:39 UTC
## Issue Description
After installing the latest client - server combination I can no longer export XML from the client. No error is reported on client or server.

## Reproduction Steps
1. Start King Phisher
2. Login
3. Open a Campaign
4. Go to File -> Export -> Campaigns -> XML
5. Observe that no file is created

## Environment Details
Client Host OS: Ubuntu 18.04 GNOME
Server Host OS: Debian 9.5
King Phisher Version: 1.12.0

## Error Details / Stack Trace
CLIENT DEBUG LOG
INFO     campaign set to REDACTED_2018_AV (id: 70)
INFO     the RPC cache has been purged
DEBUG    the rpc cache has been cleared
DEBUG    calling RPC method: graphql
DEBUG    [chan 9] Max packet in: 32768 bytes
DEBUG    [chan 9] Max packet out: 32768 bytes
DEBUG    Secsh channel 9 opened.
DEBUG    [chan 9] EOF received (9)
DEBUG    [chan 9] EOF sent (9)
DEBUG    calling RPC method: graphql
DEBUG    calling RPC method: graphql
DEBUG    calling RPC method: graphql
DEBUG    [chan 10] Max packet in: 32768 bytes
DEBUG    thread Thread-20 running king_phisher.client.tabs.campaign.loader_thread_routine in tid: 0x7f70b3fff700
DEBUG    calling RPC method: graphql
DEBUG    [chan 10] Max packet out: 32768 bytes
DEBUG    Secsh channel 10 opened.
DEBUG    [chan 11] Max packet in: 32768 bytes
DEBUG    [chan 10] EOF received (10)
DEBUG    [chan 10] EOF sent (10)
DEBUG    [chan 11] Max packet out: 32768 bytes
DEBUG    Secsh channel 11 opened.
DEBUG    [chan 12] Max packet in: 32768 bytes
DEBUG    [chan 11] EOF received (11)
DEBUG    [chan 11] EOF sent (11)
DEBUG    [chan 12] Max packet out: 32768 bytes
DEBUG    Secsh channel 12 opened.
DEBUG    [chan 13] Max packet in: 32768 bytes
DEBUG    [chan 12] EOF received (12)
DEBUG    [chan 12] EOF sent (12)
DEBUG    [chan 13] Max packet out: 32768 bytes
DEBUG    Secsh channel 13 opened.
DEBUG    thread Thread-24 running king_phisher.client.tabs.campaign.loader_thread_routine in tid: 0x7f7096a87700
DEBUG    calling RPC method: graphql
DEBUG    [chan 14] Max packet in: 32768 bytes
DEBUG    [chan 13] EOF received (13)
DEBUG    [chan 13] EOF sent (13)
DEBUG    [chan 14] Max packet out: 32768 bytes
DEBUG    Secsh channel 14 opened.
DEBUG    [chan 14] EOF received (14)
DEBUG    [chan 14] EOF sent (14)
DEBUG    calling RPC method: graphql
DEBUG    [chan 15] Max packet in: 32768 bytes
DEBUG    [chan 15] Max packet out: 32768 bytes
DEBUG    Secsh channel 15 opened.
DEBUG    [chan 15] EOF received (15)
DEBUG    [chan 15] EOF sent (15)
DEBUG    thread Thread-27 running king_phisher.client.tabs.campaign.loader_thread_routine in tid: 0x7f7097288700
DEBUG    thread Thread-28 running king_phisher.client.tabs.campaign.loader_thread_routine in tid: 0x7f70b3fff700
DEBUG    calling RPC method: events/subscribe
DEBUG    [chan 16] Max packet in: 32768 bytes
DEBUG    [chan 16] Max packet out: 32768 bytes
DEBUG    Secsh channel 16 opened.
DEBUG    [chan 16] EOF received (16)
DEBUG    [chan 16] EOF sent (16)
DEBUG    calling RPC method: events/subscribe
DEBUG    [chan 17] Max packet in: 32768 bytes
DEBUG    [chan 17] Max packet out: 32768 bytes
DEBUG    Secsh channel 17 opened.
DEBUG    [chan 17] EOF received (17)
DEBUG    [chan 17] EOF sent (17)
DEBUG    calling RPC method: events/subscribe
DEBUG    [chan 18] Max packet in: 32768 bytes
DEBUG    [chan 18] Max packet out: 32768 bytes
DEBUG    Secsh channel 18 opened.
DEBUG    [chan 18] EOF received (18)
DEBUG    [chan 18] EOF sent (18)
DEBUG    calling RPC method: graphql
DEBUG    calling RPC method: graphql
DEBUG    [chan 19] Max packet in: 32768 bytes
DEBUG    [chan 19] Max packet out: 32768 bytes
DEBUG    Secsh channel 19 opened.
DEBUG    [chan 20] Max packet in: 32768 bytes
DEBUG    [chan 19] EOF received (19)
DEBUG    [chan 19] EOF sent (19)
DEBUG    [chan 20] Max packet out: 32768 bytes
DEBUG    Secsh channel 20 opened.
DEBUG    [chan 20] EOF received (20)
DEBUG    [chan 20] EOF sent (20)
INFO     gathering campaign information for export
DEBUG    calling RPC method: graphql
DEBUG    [chan 21] Max packet in: 32768 bytes
DEBUG    [chan 21] Max packet out: 32768 bytes
DEBUG    Secsh channel 21 opened.
DEBUG    [chan 21] EOF received (21)
DEBUG    [chan 21] EOF sent (21)
INFO     unloading 1 plugins
DEBUG    plugin 'check_for_updates' has been unloaded
DEBUG    calling RPC method: logout
DEBUG    [chan 22] Max packet in: 32768 bytes
DEBUG    [chan 22] Max packet out: 32768 bytes
DEBUG    Secsh channel 22 opened.
INFO     the server event socket has been closed
DEBUG    [chan 2] EOF sent (2)
DEBUG    [chan 22] EOF received (22)
DEBUG    [chan 22] EOF sent (22)
DEBUG    shutting down the server event socket
DEBUG    Ignoring message for dead channel 2
DEBUG    Ignoring message for dead channel 2
DEBUG    Ignoring message for dead channel 22
INFO     stopped ssh port forwarding to the remote server (127.0.0.1:45447 to 127.0.0.1:80 via REDACTED:22)
DEBUG    EOF in transport thread

############# SERVER DEBUG LOG ######################
2018-11-22 16:37:46,777 KingPhisher.Server.Authentication                  INFO     successful login request from 127.0.0.1 for user dedwards
2018-11-22 16:37:46,777 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /login HTTP/1.1" 200 -
2018-11-22 16:37:46,946 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33266 tid: 0x7fb2ea3e5700 running http request handler
2018-11-22 16:37:46,986 AdvancedHTTPServer                                 INFO     127.0.0.1 "GET /_/ws/events/json HTTP/1.1" 101 -
2018-11-22 16:37:46,986 KingPhisher.Server.WebSocket.EventPublisher        INFO     web socket has been connected
2018-11-22 16:37:47,030 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33268 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:47,079 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:47,236 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33270 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:47,277 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /config/get HTTP/1.1" 200 -
2018-11-22 16:37:47,434 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33272 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:49,048 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:51,843 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33274 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:51,913 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:52,068 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33276 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:52,137 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:52,182 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33278 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:52,327 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:52,506 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33280 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:52,575 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:52,825 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33282 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:52,917 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:52,961 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33284 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:53,240 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:53,284 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33286 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:53,585 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:53,628 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33288 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:53,771 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:53,812 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33290 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:54,206 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:54,456 KingPhisher.Server.JobManager                      DEBUG    executing job with id: 681ecbaa-c2f7-49ea-b9b3-94a9993a8da1 and callback function: ping_all
2018-11-22 16:37:54,502 KingPhisher.Server.WebSocket.EventPublisher        DEBUG    received message (len: 16 opcode: 0x0a fin: True)
2018-11-22 16:37:54,503 KingPhisher.Server.WebSocket.EventPublisher        DEBUG    processing pong (opcode: 0x0a) message
2018-11-22 16:37:54,810 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33292 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:55,425 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:55,722 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33294 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:55,763 KingPhisher.Server.RPC                             DEBUG    calling RPC method rpc_events_subscribe('db-messages', attributes=['id', 'campaign_id'], event_types=['deleted', 'inserted', 'updated'])
2018-11-22 16:37:55,763 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /events/subscribe HTTP/1.1" 200 -
2018-11-22 16:37:55,925 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33296 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:55,965 KingPhisher.Server.RPC                             DEBUG    calling RPC method rpc_events_subscribe('db-visits', attributes=['id', 'campaign_id'], event_types=['deleted', 'inserted', 'updated'])
2018-11-22 16:37:55,966 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /events/subscribe HTTP/1.1" 200 -
2018-11-22 16:37:56,134 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33298 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:56,171 KingPhisher.Server.RPC                             DEBUG    calling RPC method rpc_events_subscribe('db-credentials', attributes=['id', 'campaign_id'], event_types=['deleted', 'inserted', 'updated'])
2018-11-22 16:37:56,172 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /events/subscribe HTTP/1.1" 200 -
2018-11-22 16:37:56,420 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33300 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:56,627 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:37:56,670 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33302 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:37:56,868 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:38:02,600 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33304 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:38:02,998 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
2018-11-22 16:38:06,177 KingPhisher.Server.RequestHandler                  DEBUG    127.0.0.1:33306 tid: 0x7fb2e9be4700 running http request handler
2018-11-22 16:38:06,218 KingPhisher.Server.RPC                             DEBUG    calling RPC method rpc_logout()
2018-11-22 16:38:06,219 KingPhisher.Server.Authentication                  INFO     successful logout request from 127.0.0.1 for user 1
2018-11-22 16:38:06,219 AdvancedHTTPServer                                 INFO     127.0.0.1 "RPC /logout HTTP/1.1" 200 -
2018-11-22 16:38:06,259 KingPhisher.Server.WebSocket.EventPublisher        DEBUG    received message (len: 2 opcode: 0x08 fin: True)
2018-11-22 16:38:06,259 KingPhisher.Server.WebSocket.EventPublisher        DEBUG    processing close (opcode: 0x08) message
2018-11-22 16:38:24,494 KingPhisher.Server.JobManager                      DEBUG    executing job with id: 681ecbaa-c2f7-49ea-b9b3-94a9993a8da1 and callback function: ping_all
2018-11-22 16:38:54,532 KingPhisher.Server.JobManager                      DEBUG    executing job with id: 681ecbaa-c2f7-49ea-b9b3-94a9993a8da1 and callback function: ping_all

**Comment by wolfthefallen** [comment] 2018-11-22 16:48
@scandox From your client logs I can see that you started the export process from the line of `INFO gathering campaign information for export`.. For large campaigns this will take some time, as the client will request all the campaign information, then process it. Then it will create the XML file.

Please try exporting it again and wait for while. If it is a really really large campaign this could take a few minutes. Once the processing is complete it, the logs will say `INFO completed processing campaign information for export`. At that point it will start to the xml file to disk. Once that is completed, you will see another log entry of `INFO campaign export complete`

**Comment by zeroSteiner** [comment] 2018-11-22 19:10
I'm pretty sure I remember seeing and fixing this issue. I'm not by my computer right now though so I can't check the logs. Can you update to the dev branch and see if you can still reproduce it?

**Comment by zeroSteiner** [comment] 2018-11-22 19:13
Nevermind I think this is the commit where I fixed it. https://github.com/securestate/king-phisher/commit/369e46e2f0838a028965eb15a61f147aa0feb747 @wolfthefallen prior to that the GUI was hanging while trying to export XML. Because the issue wasn't reported at the time I just fixed it in dev and moved on.

**Comment by scandox** [comment] 2018-11-22 23:43
I checked out dev branch (had to do it for both server and client or it reported an incompatible API). Anyway that works. Thanks for your help.

**Comment by zeroSteiner** [comment] 2018-11-23 00:38
Awesome thanks for letting us know. I'm going to close this out now. Unfortunately due to the database changes it's not practical for us to merge just that change into master so this was the best option I could think of.

**Closed** 2018-11-23 00:39 UTC
Labels: bug, client, duplicate
