### ISSUE TITLE
MSI does not respect install directory

### ISSUE THREAD

**Issue by uyh39f** [securestate/king-phisher#287] opened 2018-04-04 19:59 UTC
## Issue Description
Windows Client installer drops files in root of c: instead of the requested install directory

## Reproduction Steps
1. Begin MSI install
2. During MSI install, specify that kingphisher should be installed to c:\program files(x86)\kingphisher
3. Complete installation
4. View files added to C:\

## Environment Details

Host OS: Windows 10
King Phisher Version: 1.10.0

## Error Details / Stack Trace
N/A

**Comment by wolfthefallen** [comment] 2018-04-04 20:31
I am unable to recreate this issue in Windows 10 or Windows 7. The msi is install to the default path of `c:\Program Files (x86\KingPisher\` or custom location that is manually entered. 

Can you please provide any more information on the steps you are taking? Particularly what are you entering in the Select destination directory box?

**Comment by uyh39f** [comment] 2018-04-04 20:34
Here's a screenshot of the Select Destination pane.  The next thing I'd do is to select "next"
![kp](https://user-images.githubusercontent.com/38084108/38333218-9574c96a-381d-11e8-8b04-a21b029ad26e.PNG)

**Comment by wolfthefallen** [comment] 2018-04-04 20:40
Thank you for the additional information, I have tried to reproduce this issue in Windows 7 x86, Windows 7 x64, and Windows 10. Both on hardware and in VM, and I am unable to reproduce this issue.

Can you please confirm the hashes of your MSI file match the hashes for the [release](https://github.com/securestate/king-phisher/release).

**Comment by zeroSteiner** [comment] 2018-04-04 20:42
Also does `C:\Program Files (x86)` exist on your system?

**Comment by uyh39f** [comment] 2018-04-04 20:48
Just checked MD5 and SHA1, both match.  And @zeroSteiner yes, the folder exists, I even checked to confirm. ;)

**Comment by uyh39f** [comment] 2018-04-04 20:49
I'm running this on bare metal, FWIW.

**Comment by zeroSteiner** [comment] 2018-04-04 20:50
Is there anything else out of the ordinary in your environment? Does KP work when it's installed and ends up in `C:\` Also when it does end up in `C:\` are there just a bunch of files there or are they contained within a `C:\KingPhisher` directory?

**Comment by uyh39f** [comment] 2018-04-04 20:55
Yes it does run straight out of C:.  It looks like it's using c: as the root of it's install directory, so (as far as I can tell) everything it would normally install to it's own folder goes to C: instead.

**Comment by zeroSteiner** [comment] 2018-04-04 21:25
Well we've done all we can to reproduce this. We've gotten no where so I'm going to close this issue out. If you think of any relevant information that might help us reproduce this behavior just comment on it here and we'll reopen the issue. Thanks for reporting this.

**Closed by zeroSteiner** 2018-04-04 21:25 UTC
Labels: bug, can't reproduce, client, install
