### ISSUE TITLE
Cannot See the KingPhisher Framework Settings

### ISSUE THREAD

**Issue by bhavinmackk** [securestate/king-phisher#200] opened 2017-03-24 05:46 UTC
I have been working on the King-Phisher framework since a while, I have a noticed some weird changes in my framework, for example: I cannot see the menu bar on top of the framework while its loaded (where you have options like file, edit, etc.) Below is a sample snapshot:-

![image](https://cloud.githubusercontent.com/assets/7046389/24282017/f090e18a-1082-11e7-987d-8630295fbd1d.png)

Because of this issue, when I try to send emails on the target system I get an error saying one or more source email is invalid (because it skips the SPF policy check) and does not connect to the SMTP server. Now, before launching the emails, ideally a pop-screen shows up which allows us to enter SMTP credentials, however, this step is skipped and the framework readily tries to send emails and fails.

![image](https://cloud.githubusercontent.com/assets/7046389/24282061/40fbe7f0-1083-11e7-9d85-72e7a7104cfe.png)

**Comment by zeroSteiner** [comment] 2017-03-24 08:20
I'm guessing you're using Ubuntu is that right?

**Comment by bhavinmackk** [comment] 2017-03-24 09:23
That is correct. Ubuntu 14.04! I read a previous post (now issue is closed) on this same issue and installed the unity theme. However, whenever I reboot my instance after installation, the OS does not load.

**Comment by wolfthefallen** [comment] 2017-03-24 10:36
When programs are opened in Ubuntu unity, the menu bar of the application is moved to the top bar of the OS desktop. Hover your mouse over the bar at the very top of your screen you will see it change to the menu bar of King Phisher application when it is in focus.

**Comment by bhavinmackk** [comment] 2017-03-24 10:54
@wolfthefallen I have considered that option, but hovering the mouse over the menu doesn't really show anything. Check this out:-

![image](https://cloud.githubusercontent.com/assets/7046389/24291282/4592e27a-10ae-11e7-8433-45dc8de9a170.png)

**Comment by zeroSteiner** [comment] 2017-03-24 12:19
This is a duplicate of #190. What version of King Phisher are you using? @wolfthefallen issued a patch to install the necessary Adwaita theme data to fix the King Phisher client when installed in Unity.

**Comment by wolfthefallen** [comment] 2017-03-24 12:45
Hover your mouse over the area that says `King Phisher` in the top left of the screen to get your menu bar on a unity desktop.

![unity_menu_bar](https://cloud.githubusercontent.com/assets/9035933/24294747/28752a58-106e-11e7-8dd7-51b25e6fb057.png)

**Comment by bhavinmackk** [comment] 2017-03-24 15:58
@wolfthefallen Check this out:-

![image](https://cloud.githubusercontent.com/assets/7046389/24302457/b7d8dc66-10d8-11e7-9fa7-10dd0d812db5.png)

From your previous post I saw few pointers such as installing the Adwaita-theme, theme icons, still no luck.

**Comment by wolfthefallen** [comment] 2017-03-24 21:03
I cannot reproduce this issue on Ubuntu 14.04 Unity.
Normal settings for the menu bars is set in system settings > Appearance. You can select to have it in the menu bar or in the windows title bar.

**Comment by zeroSteiner** [comment] 2017-03-31 15:16
This hasn't been updated in a week so I'm going to close it out.

**Closed by zeroSteiner** 2017-03-31 15:16 UTC
Labels: can't reproduce, help me
